import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/molecules/navigation";
import { Footer } from "@/components/organisms/footer";

const clashDisplay = localFont({
  src: "./fonts/ClashDisplayVF.ttf",
  variable: "--font-clash-display",
  weight: "100 200 300 400 500 600 700 800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} antialiased`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
